In [1]:
using BSON

In [29]:
bson("test.bson", Dict(:a => [1+2im, 3+4im], :b => "Hello, World!"))

In [30]:
BSON.load("test.bson")

Dict{Symbol,Any} with 2 entries:
  :a => Complex{Int64}[1+2im, 3+4im]
  :b => "Hello, World!"

In [31]:
A=[1,[2,3]]

2-element Array{Any,1}:
 1      
  [2, 3]

In [36]:
bson("test2.bson",a=A[1], b=A[2])

In [37]:
BSON.load("test2.bson")

Dict{Symbol,Any} with 2 entries:
  :a => 1
  :b => [2, 3]

In [38]:
A=[1, [2,3], [4,5,7]]

3-element Array{Any,1}:
 1         
  [2, 3]   
  [4, 5, 7]

In [40]:
for items in A
    @save "test2.bson" item
end

LoadError: UndefVarError: @save not defined

In [2]:
using BSON: @save, @load

In [43]:
for items in A
    @save "test2.bson" items
end

In [46]:
BSON.load("test2.bson")

Dict{Symbol,Any} with 1 entry:
  :A => Any[1, [2, 3], [4, 5, 7]]

In [45]:
@save "test2.bson" A

In [49]:
c=Dict{}

Dict

In [60]:
for (n, f) in enumerate(A)
     c[n]=f
end

MethodError: MethodError: no method matching setindex!(::Type{Dict}, ::Int64, ::Int64)

In [53]:
A

3-element Array{Any,1}:
 1         
  [2, 3]   
  [4, 5, 7]

In [78]:
A=[.2, .4 ,4 ,.6, 7]

5-element Array{Float64,1}:
 0.2
 0.4
 4.0
 0.6
 7.0

In [80]:
fvars = Dict()
for n=1:5
    for k=1:5
       fvars[A[n],k] = n^2,k*3
    end
end
fvars

Dict{Any,Any} with 25 entries:
  (4.0, 3) => (9, 9)
  (7.0, 2) => (25, 6)
  (4.0, 4) => (9, 12)
  (0.2, 3) => (1, 9)
  (0.2, 4) => (1, 12)
  (0.6, 5) => (16, 15)
  (0.4, 5) => (4, 15)
  (0.6, 3) => (16, 9)
  (7.0, 4) => (25, 12)
  (7.0, 1) => (25, 3)
  (0.4, 2) => (4, 6)
  (4.0, 5) => (9, 15)
  (7.0, 5) => (25, 15)
  (0.2, 5) => (1, 15)
  (0.6, 1) => (16, 3)
  (0.2, 1) => (1, 3)
  (0.6, 4) => (16, 12)
  (7.0, 3) => (25, 9)
  (0.4, 3) => (4, 9)
  (0.2, 2) => (1, 6)
  (0.6, 2) => (16, 6)
  (0.4, 1) => (4, 3)
  (4.0, 1) => (9, 3)
  (4.0, 2) => (9, 6)
  (0.4, 4) => (4, 12)

In [83]:
fvars[(7.0,1)]

(25, 3)

In [23]:
function sq(x)
    x[1]+x[2]
end

sq (generic function with 1 method)

In [16]:
    width = 2.5; height=5
    n_iter_Q = 10;n_iter_P = 2*n_iter_Q; N = n_iter_P * n_iter_Q;
    ArrP = range(-width, stop = width, length = n_iter_P)
    ArrQ = range(-height, stop = height, length = n_iter_Q)
    mesh_P=[P for Q in ArrQ, P in ArrP]
    mesh_Q=[Q for Q in ArrQ, P in ArrP]
    mesh = [(P, Q) for Q in ArrQ, P in ArrP]

10×20 Array{Tuple{Float64,Float64},2}:
 (-2.5, -5.0)       (-2.23684, -5.0)       …  (2.5, -5.0)     
 (-2.5, -3.88889)   (-2.23684, -3.88889)      (2.5, -3.88889) 
 (-2.5, -2.77778)   (-2.23684, -2.77778)      (2.5, -2.77778) 
 (-2.5, -1.66667)   (-2.23684, -1.66667)      (2.5, -1.66667) 
 (-2.5, -0.555556)  (-2.23684, -0.555556)     (2.5, -0.555556)
 (-2.5, 0.555556)   (-2.23684, 0.555556)   …  (2.5, 0.555556) 
 (-2.5, 1.66667)    (-2.23684, 1.66667)       (2.5, 1.66667)  
 (-2.5, 2.77778)    (-2.23684, 2.77778)       (2.5, 2.77778)  
 (-2.5, 3.88889)    (-2.23684, 3.88889)       (2.5, 3.88889)  
 (-2.5, 5.0)        (-2.23684, 5.0)           (2.5, 5.0)      

In [126]:
T=map(sq,mesh)

10×20 Array{Float64,2}:
 -7.5       -7.23684   -6.97368   …  -3.02632   -2.76316   -2.5     
 -6.38889   -6.12573   -5.86257      -1.9152    -1.65205   -1.38889 
 -5.27778   -5.01462   -4.75146      -0.804094  -0.540936  -0.277778
 -4.16667   -3.90351   -3.64035       0.307018   0.570175   0.833333
 -3.05556   -2.7924    -2.52924       1.41813    1.68129    1.94444 
 -1.94444   -1.68129   -1.41813   …   2.52924    2.7924     3.05556 
 -0.833333  -0.570175  -0.307018      3.64035    3.90351    4.16667 
  0.277778   0.540936   0.804094      4.75146    5.01462    5.27778 
  1.38889    1.65205    1.9152        5.86257    6.12573    6.38889 
  2.5        2.76316    3.02632       6.97368    7.23684    7.5     

In [134]:
SAVE_DATA=Dict("escape_times"=>T, "mesh"=>mesh, "ArrP"=>ArrP, "ArrQ"=>ArrQ)

# for k=1:n_iter_Q
#     for j=1:n_iter_P
#         SAVE_DATA[(ArrQ[k],ArrP[j])]=T[k,j]
#     end
# end

Dict{String,AbstractArray} with 4 entries:
  "ArrQ"         => -5.0:1.1111111111111112:5.0
  "ArrP"         => -2.5:0.2631578947368421:2.5
  "mesh"         => Tuple{Float64,Float64}[(-2.5, -5.0) (-2.23684, -5.0) … (2.2…
  "escape_times" => [-7.5 -7.23684 … -2.76316 -2.5; -6.38889 -6.12573 … -1.6520…

In [132]:
SAVE_DATA["mesh"]

10×20 Array{Tuple{Float64,Float64},2}:
 (-2.5, -5.0)       (-2.23684, -5.0)       …  (2.5, -5.0)     
 (-2.5, -3.88889)   (-2.23684, -3.88889)      (2.5, -3.88889) 
 (-2.5, -2.77778)   (-2.23684, -2.77778)      (2.5, -2.77778) 
 (-2.5, -1.66667)   (-2.23684, -1.66667)      (2.5, -1.66667) 
 (-2.5, -0.555556)  (-2.23684, -0.555556)     (2.5, -0.555556)
 (-2.5, 0.555556)   (-2.23684, 0.555556)   …  (2.5, 0.555556) 
 (-2.5, 1.66667)    (-2.23684, 1.66667)       (2.5, 1.66667)  
 (-2.5, 2.77778)    (-2.23684, 2.77778)       (2.5, 2.77778)  
 (-2.5, 3.88889)    (-2.23684, 3.88889)       (2.5, 3.88889)  
 (-2.5, 5.0)        (-2.23684, 5.0)           (2.5, 5.0)      

In [3]:
@save "test_data" SAVE_DATA


UndefVarError: UndefVarError: SAVE_DATA not defined

In [37]:
SAVE_DATA=Dict()

Dict{Any,Any} with 0 entries

In [4]:
@load "escape_data0_2000000000000.bson" SAVE_DATA


In [5]:
SAVE_DATA

Dict{String,Any} with 5 entries:
  "ArrQ"         => -5.0:0.10101010101010101:5.0
  "ArrP"         => -2.5:0.02512562814070352:2.5
  "Energy"       => 0.2
  "mesh"         => Tuple{Float64,Float64}[(-2.5, -5.0) (-2.47487, -5.0) … (2.4…
  "escape_times" => [NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN NaN … NaN Na…

In [62]:
X=zeros(length)
for (key,val) in SAVE_DATA
    println(key)
    #     Q_PSS,P_PSS=SAVE_DATA[c]
#     current_color=Brandons_Colors[mod(color_counter,length(Brandons_Colors))+1]
#     plot(Q_PSS,P_PSS,",",c=current_color);
end

(2.7777777777777777, -2.5)
0.2777777777777777
(5.0, -0.39473684210526316)
4.605263157894737
(-5.0, -0.6578947368421053)
-5.657894736842105
(0.5555555555555556, 1.4473684210526316)
2.002923976608187
(-2.7777777777777777, 1.7105263157894737)
-1.067251461988304
(3.888888888888889, -2.236842105263158)
1.6520467836257309
(-3.888888888888889, 0.9210526315789473)
-2.9678362573099415
(-1.6666666666666667, -1.7105263157894737)
-3.3771929824561404
(1.6666666666666667, 0.6578947368421053)
2.3245614035087723
(2.7777777777777777, 0.13157894736842105)
2.909356725146199
(-0.5555555555555556, 1.4473684210526316)
0.8918128654970761
(2.7777777777777777, -0.13157894736842105)
2.6461988304093564
(-2.7777777777777777, -1.1842105263157894)
-3.961988304093567
(-2.7777777777777777, 0.9210526315789473)
-1.8567251461988303
(1.6666666666666667, 1.7105263157894737)
3.3771929824561404
(-3.888888888888889, 2.5)
-1.3888888888888888
(-2.7777777777777777, -2.236842105263158)
-5.014619883040936
(-3.888888888888889, 1.9

(2.7777777777777777, 0.39473684210526316)
3.172514619883041
(3.888888888888889, 0.6578947368421053)
4.546783625730994
(-0.5555555555555556, 1.9736842105263157)
1.4181286549707601
(-5.0, 1.1842105263157894)
-3.8157894736842106
(-3.888888888888889, -1.7105263157894737)
-5.599415204678363
(2.7777777777777777, 0.9210526315789473)
3.698830409356725
(2.7777777777777777, 0.6578947368421053)
3.435672514619883
(2.7777777777777777, 1.1842105263157894)
3.961988304093567
(-3.888888888888889, -2.5)
-6.388888888888889
(0.5555555555555556, 1.7105263157894737)
2.2660818713450293
(-0.5555555555555556, 0.13157894736842105)
-0.42397660818713456
(-3.888888888888889, -0.39473684210526316)
-4.283625730994152
(5.0, 0.9210526315789473)
5.921052631578947
(-2.7777777777777777, 0.6578947368421053)
-2.1198830409356724
(-0.5555555555555556, -1.7105263157894737)
-2.2660818713450293
(-2.7777777777777777, 0.13157894736842105)
-2.6461988304093564
(-1.6666666666666667, -1.9736842105263157)
-3.6403508771929824
(5.0, -1.

In [106]:
X=collect(values(SAVE_DATA))


200-element Array{Any,1}:
 (2.7777777777777777, -2.5)                
 (5.0, -0.39473684210526316)               
 (-5.0, -0.6578947368421053)               
 (0.5555555555555556, 1.4473684210526316)  
 (-2.7777777777777777, 1.7105263157894737) 
 (3.888888888888889, -2.236842105263158)   
 (-3.888888888888889, 0.9210526315789473)  
 (-1.6666666666666667, -1.7105263157894737)
 (1.6666666666666667, 0.6578947368421053)  
 (2.7777777777777777, 0.13157894736842105) 
 (-0.5555555555555556, 1.4473684210526316) 
 (2.7777777777777777, -0.13157894736842105)
 (-2.7777777777777777, -1.1842105263157894)
 ⋮                                         
 (2.7777777777777777, 0.6578947368421053)  
 (2.7777777777777777, 1.1842105263157894)  
 (-3.888888888888889, -2.5)                
 (0.5555555555555556, 1.7105263157894737)  
 (-0.5555555555555556, 0.13157894736842105)
 (-3.888888888888889, -0.39473684210526316)
 (5.0, 0.9210526315789473)                 
 (-2.7777777777777777, 0.6578947368421053) 
 (-0.5

In [118]:
x=zeros(length(X))
y=zeros(length(X))
for index in 1:length(X)
    x[index],y[index]=X[index]
end

In [103]:
x

200-element Array{Float64,1}:
  2.7777777777777777
  5.0               
 -5.0               
  0.5555555555555556
 -2.7777777777777777
  3.888888888888889 
 -3.888888888888889 
 -1.6666666666666667
  1.6666666666666667
  2.7777777777777777
 -0.5555555555555556
  2.7777777777777777
 -2.7777777777777777
  ⋮                 
  2.7777777777777777
  2.7777777777777777
 -3.888888888888889 
  0.5555555555555556
 -0.5555555555555556
 -3.888888888888889 
  5.0               
 -2.7777777777777777
 -0.5555555555555556
 -2.7777777777777777
 -1.6666666666666667
  5.0               

In [90]:
X[1]

(2.7777777777777777, -2.5)

In [95]:
(a,b)=X[1]

(2.7777777777777777, -2.5)

In [96]:
a

2.7777777777777777

In [97]:
b

-2.5

In [104]:
Z

UndefVarError: UndefVarError: Z not defined

In [116]:
Z=collect(values(SAVE_DATA));Z=Z[1:end-1]

199-element Array{Any,1}:
  0.2777777777777777 
  4.605263157894737  
 -5.657894736842105  
  2.002923976608187  
 -1.067251461988304  
  1.6520467836257309 
 -2.9678362573099415 
 -3.3771929824561404 
  2.3245614035087723 
  2.909356725146199  
  0.8918128654970761 
  2.6461988304093564 
 -3.961988304093567  
  ⋮                  
  3.698830409356725  
  3.435672514619883  
  3.961988304093567  
 -6.388888888888889  
  2.2660818713450293 
 -0.42397660818713456
 -4.283625730994152  
  5.921052631578947  
 -2.1198830409356724 
 -2.2660818713450293 
 -2.6461988304093564 
 -3.6403508771929824 

In [7]:
using PyCall
pygui(:qt)
using PyPlot
pygui(true)

true

In [31]:
M = rand(10, 10)
contourf(mesh_Q,mesh_P,Z)

PyObject <matplotlib.contour.QuadContourSet object at 0x7f3700616a20>

In [29]:
X=SAVE_DATA["ArrQ"]
Y=SAVE_DATA["ArrP"]
pcolormesh(mesh_Q,mesh_P,Z)

PyObject <matplotlib.collections.QuadMesh object at 0x7f37007e1400>

In [16]:
Z=log1p.(SAVE_DATA["escape_times"])

100×200 Array{Float64,2}:
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  …  NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  …  NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  …  NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  Na

In [19]:
SAVE_DATA["mesh"][1]

(-2.5, -5.0)

In [20]:
ArrQ=SAVE_DATA["ArrQ"]
ArrP=SAVE_DATA["ArrP"]
mesh_P=[P for Q in ArrQ, P in ArrP]
mesh_Q=[Q for Q in ArrQ, P in ArrP]


100×200 Array{Float64,2}:
 -5.0      -5.0      -5.0      -5.0      …  -5.0      -5.0      -5.0    
 -4.89899  -4.89899  -4.89899  -4.89899     -4.89899  -4.89899  -4.89899
 -4.79798  -4.79798  -4.79798  -4.79798     -4.79798  -4.79798  -4.79798
 -4.69697  -4.69697  -4.69697  -4.69697     -4.69697  -4.69697  -4.69697
 -4.59596  -4.59596  -4.59596  -4.59596     -4.59596  -4.59596  -4.59596
 -4.49495  -4.49495  -4.49495  -4.49495  …  -4.49495  -4.49495  -4.49495
 -4.39394  -4.39394  -4.39394  -4.39394     -4.39394  -4.39394  -4.39394
 -4.29293  -4.29293  -4.29293  -4.29293     -4.29293  -4.29293  -4.29293
 -4.19192  -4.19192  -4.19192  -4.19192     -4.19192  -4.19192  -4.19192
 -4.09091  -4.09091  -4.09091  -4.09091     -4.09091  -4.09091  -4.09091
 -3.9899   -3.9899   -3.9899   -3.9899   …  -3.9899   -3.9899   -3.9899 
 -3.88889  -3.88889  -3.88889  -3.88889     -3.88889  -3.88889  -3.88889
 -3.78788  -3.78788  -3.78788  -3.78788     -3.78788  -3.78788  -3.78788
  ⋮                      

In [23]:
mesh_Q

100×200 Array{Float64,2}:
 -5.0      -5.0      -5.0      -5.0      …  -5.0      -5.0      -5.0    
 -4.89899  -4.89899  -4.89899  -4.89899     -4.89899  -4.89899  -4.89899
 -4.79798  -4.79798  -4.79798  -4.79798     -4.79798  -4.79798  -4.79798
 -4.69697  -4.69697  -4.69697  -4.69697     -4.69697  -4.69697  -4.69697
 -4.59596  -4.59596  -4.59596  -4.59596     -4.59596  -4.59596  -4.59596
 -4.49495  -4.49495  -4.49495  -4.49495  …  -4.49495  -4.49495  -4.49495
 -4.39394  -4.39394  -4.39394  -4.39394     -4.39394  -4.39394  -4.39394
 -4.29293  -4.29293  -4.29293  -4.29293     -4.29293  -4.29293  -4.29293
 -4.19192  -4.19192  -4.19192  -4.19192     -4.19192  -4.19192  -4.19192
 -4.09091  -4.09091  -4.09091  -4.09091     -4.09091  -4.09091  -4.09091
 -3.9899   -3.9899   -3.9899   -3.9899   …  -3.9899   -3.9899   -3.9899 
 -3.88889  -3.88889  -3.88889  -3.88889     -3.88889  -3.88889  -3.88889
 -3.78788  -3.78788  -3.78788  -3.78788     -3.78788  -3.78788  -3.78788
  ⋮                      