In [1]:
using ProgressMeter
using Printf
using BSON: @save, @load
using PyCall
pygui(:qt)
using PyPlot
pygui(true)
include("escape_dimer_one_hit.jl")
H=.22

┌ Info: Recompiling stale cache file /home/brandon_behring/.julia/compiled/v1.2/PyCall/GkzkC.ji for PyCall [438e738f-606a-5dbb-bf0a-cddfbfd45ab0]
└ @ Base loading.jl:1240
┌ Info: Recompiling stale cache file /home/brandon_behring/.julia/compiled/v1.2/PyPlot/oatAj.ji for PyPlot [d330b81b-6aea-500a-939a-2ce795aea3ee]
└ @ Base loading.jl:1240


0.22

In [2]:
t_end = 1e3
width = 2.25; height =4.5
n_iter_P = 100;n_iter_Q =100;
N = n_iter_P * n_iter_Q;
ArrQ = range(-width, stop = width, length = n_iter_Q)
ArrP = range(0, stop = height, length = n_iter_P)
mesh = [(Q, P) for Q in ArrQ, P in ArrP]
mesh_list = reshape(mesh, 1, :)
t_list = t_end * ones(N);
Energy = H* ones(N);

h = replace(@sprintf("%.13f",H), "." => "_")
nQ = @sprintf("_%d",n_iter_Q)
nP = @sprintf("_%d",n_iter_P)
h_BSON="num_hhits_escape_data"*h*nQ*nP*".bson"
location = "/mnt/bdd38f66-9ece-451a-b915-952523c139d2/Escape/"
println(h_BSON)
one_hit_exit=[]

num_hhits_escape_data0_2200000000000_100_100.bson


0-element Array{Any,1}

In [3]:
include("escape_dimer_one_hit.jl")
exit_points= @showprogress map(escape_after_one_hit, mesh_list, t_list, Energy);
cleaned_points=[]
for item in exit_points
    if item!=nothing
        push!(cleaned_points, item)
    end
end
cleaned_points
Q0,P0,Q1,P1=unzipper3(cleaned_points)
Q_0=vcat(Q0,-Q0); P_0=vcat(P0,-P0);
Q_1=vcat(Q1,-Q1); P_1=vcat(P1,-P1);
plot(Q_0,P_0, ".",markersize=1,c=:blue);
plot(Q_1,P_1, ".",markersize=1,c=:red);
xlim(-2.5,2.5) 
ylim(-4.5,4.5) ;

Progress: 100%|█████████████████████████████████████████| Time: 0:00:593:05


In [4]:
exit_points

10000-element Array{Union{Nothing, Tuple{Int64,Float64,Float64,Float64,Float64,Float64,Float64,Float64}},1}:
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 ⋮      
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing

In [5]:
Q0,P0,Q1,P1=unzipper3(cleaned_points)
Q_0=vcat(Q0,-Q0); P_0=vcat(P0,-P0);
Q_1=vcat(Q1,-Q1); P_1=vcat(P1,-P1);
plot(Q_0,P_0, ".",markersize=1,c=:blue);
plot(Q_1,P_1, ".",markersize=1,c=:red);
xlim(-2.5,2.5) 
ylim(-4.5,4.5) ;

In [6]:
cleaned_points

725-element Array{Any,1}:
 (0, -1.3863636363636365, 0.6135331487539595, 0.0, 3.739740135899555e-16, -0.5946491183532561, 0.4442305821411961, 2.4554001049061975)               
 (0, -1.3409090909090908, 0.5908885858131729, 0.0, 1.232181681798617e-16, -0.9429562114325443, 0.5430339372692075, 2.2904416666647003)               
 (0, -1.2954545454545454, 0.5700004087791751, 0.0, -1.3698511862005405e-16, -1.116480116851568, 0.6089185586599603, 2.1512435339666043)              
 (0, -1.25, 0.550791581576226, 0.0, 4.1066228496232755e-17, -1.2234520062389092, 0.6479311898359523, 2.0211197749319467)                             
 (0, -1.2045454545454546, 0.5332008659222875, 0.0, 2.0232982611045478e-16, -1.2937546328656535, 0.6641328488006596, 1.889701681348685)               
 (0, -1.1590909090909092, 0.5171814951517396, 0.0, 2.6912825417713196e-16, -1.3400608265931142, 0.6615906373279072, 1.7507420479635232)              
 (0, -1.0681818181818181, 0.48973791932380323, 0.0, -1.0762319641870393e-1

In [7]:
sol[4,1]

UndefVarError: UndefVarError: sol not defined

In [8]:
function add_eight!(point,radius, one_hit_exit, t_end, energy)
    X=point[2]
    Y=point[4]
    
    X_plus=X+radius
    Y_plus=Y+radius
    X_minus=X-radius
    Y_minus=Y-radius
    
    
    point_1=[X_minus, Y_plus]
    point_2=[X, Y_plus]
    point_3=[X_minus, Y_plus]
    
    point_4=[X_minus, Y]
    point_5=[X_plus, Y]
    
    point_6=[X_minus, Y_minus]
    point_7=[X, Y_minus]
    point_8=[X_minus, Y_minus];
    
    
    new_points= [point_1, point_2, point_3, point_4, point_5, point_6, point_7, point_8]
    for point in new_points
        new_point=escape_after_one_hit(point,t_end,energy)
        if new_point!=nothing
            push!(one_hit_exit, new_point)
        end
    end
end

add_eight! (generic function with 1 method)

In [9]:
function add_four!(point,radius, one_hit_exit, t_end, energy)
    X=point[2]
    Y=point[4]
    
    X_plus=X+radius
    Y_plus=Y+radius
    X_minus=X-radius
    Y_minus=Y-radius
    
    
    point_2=[X, Y_plus]
    
    point_4=[X_minus, Y]
    
    point_5=[X_plus, Y]
    
    point_7=[X, Y_minus]
    
    
    new_points= [point_2, point_4, point_5, point_7]
      for point in new_points
        new_point=escape_after_one_hit(point,t_end,energy)
        if new_point!=nothing
            push!(one_hit_exit, new_point)
        end
    end
end

add_four! (generic function with 1 method)

In [10]:
function addpoint!(list)
    push!(list,[-10,10])
end

addpoint! (generic function with 1 method)

In [11]:
function unzipper2(array_of_points)
    N=length(array_of_points)
    Q=zeros(N)
    P=zeros(N)
    for (index,point) in enumerate(array_of_points)
        Q[index]=point[2]
        P[index]=point[4]
    end
    return Q,P
end

unzipper2 (generic function with 1 method)

In [12]:
function unzipper3(array_of_points)
    N=length(array_of_points)
    Q0=zeros(N)
    P0=zeros(N)
    Q1=zeros(N)
    P1=zeros(N)
    for (index,point) in enumerate(array_of_points)
        Q0[index]=point[2]
        P0[index]=point[4]
        Q1[index]=point[6]
        P1[index]=point[8]
    end
    return Q0,P0,Q1,P1
end

unzipper3 (generic function with 1 method)

In [13]:
Q0,P0,Q1,P1=unzipper3(new_forward)
plot(Q0,P0, ".",markersize=1,c=:blue);
plot(Q1,P1, ".",markersize=1,c=:red);
xlim(-2.5,2.5) 
ylim(-4.5,4.5) ;

UndefVarError: UndefVarError: new_forward not defined

In [14]:
old_list=copy(cleaned_points)
energy=.25
radius=.1

@showprogress for (index,point) in enumerate(old_list)
    add_eight!(point,radius, cleaned_points, t_end, energy)
end
cleaned_points
length(cleaned_points)
Q0,P0,Q1,P1=unzipper3(cleaned_points)
Q_0=vcat(Q0,-Q0); P_0=vcat(P0,-P0);
Q_1=vcat(Q1,-Q1); P_1=vcat(P1,-P1);
plot(Q_0,P_0, ".",markersize=1,c=:blue);
plot(Q_1,P_1, ".",markersize=1,c=:red);
xlim(-2.5,2.5) 
ylim(-4.5,4.5) ;

Progress: 100%|█████████████████████████████████████████| Time: 0:00:28


In [15]:
Q,P=unzipper2(cleaned_points)
Q_one=vcat(Q,-Q); P_one=vcat(P,-P);
plot(Q_one,P_one, ".",markersize=1,c=:blue);

In [16]:
cleaned_points

3931-element Array{Any,1}:
 (0, -1.3863636363636365, 0.6135331487539595, 0.0, 3.739740135899555e-16, -0.5946491183532561, 0.4442305821411961, 2.4554001049061975)              
 (0, -1.3409090909090908, 0.5908885858131729, 0.0, 1.232181681798617e-16, -0.9429562114325443, 0.5430339372692075, 2.2904416666647003)              
 (0, -1.2954545454545454, 0.5700004087791751, 0.0, -1.3698511862005405e-16, -1.116480116851568, 0.6089185586599603, 2.1512435339666043)             
 (0, -1.25, 0.550791581576226, 0.0, 4.1066228496232755e-17, -1.2234520062389092, 0.6479311898359523, 2.0211197749319467)                            
 (0, -1.2045454545454546, 0.5332008659222875, 0.0, 2.0232982611045478e-16, -1.2937546328656535, 0.6641328488006596, 1.889701681348685)              
 (0, -1.1590909090909092, 0.5171814951517396, 0.0, 2.6912825417713196e-16, -1.3400608265931142, 0.6615906373279072, 1.7507420479635232)             
 (0, -1.0681818181818181, 0.48973791932380323, 0.0, -1.0762319641870393e-16, -1

In [17]:
SAVE_DATA=Dict("one_hit_exit"=>one_hit_exit)


Dict{String,Array{Any,1}} with 1 entry:
  "one_hit_exit" => Any[]

In [18]:
include("forward_one.jl")

forward_one (generic function with 1 method)

In [19]:
new_forward=[]

@showprogress for point in cleaned_points
    forward_point=forward_one(point, t_end, H)
    if forward_point!=nothing
        push!(new_forward,forward_point)
    end
end
new_forward

Progress: 100%|█████████████████████████████████████████| Time: 0:02:52m41


724-element Array{Any,1}:
 (1.8949151302491236e-15, -0.5945647385530974, 0.4443489822176144, 2.45549299299467)   
 (-3.45002699132114e-16, -0.9428100623346155, 0.5432209328415848, 2.290660166336763)   
 (6.290719057741426e-15, -1.1163830949437608, 0.6090465659856197, 2.151448219370238)   
 (2.6574354804771087e-16, -1.2232447041922614, 0.6480595145870632, 2.021499521759234)  
 (1.40286206962993e-16, -1.2936731059493658, 0.6642634388024408, 1.8899455425607745)   
 (1.6394087933749738e-16, -1.3399839393685835, 0.6618097500415243, 1.7511145171952496) 
 (7.176441348697169e-16, -1.3797496190802216, 0.6200721049845646, 1.4436649926739948)  
 (-4.698269272602047e-17, -1.3760030118930193, 0.5899825894769714, 1.2734739541490203) 
 (1.4671805661602813e-14, -1.3548813695136361, 0.5583702694252126, 1.0894367855449396) 
 (-3.7684262818674675e-15, 1.354881369513636, 0.5583702694252132, -1.089436785544958)  
 (-3.788080696790967e-15, 1.3760030118930189, 0.5899825894769711, -1.2734739541490203) 
 (1.92

In [20]:
Q,P=unzipper2(new_forward)
Q_escape=vcat(Q,-Q); P_escape=vcat(P,-P);
Q,P=unzipper2(cleaned_points)
Q_one=vcat(Q,-Q); P_one=vcat(P,-P);
# plot(Q_one,P_one, ".",markersize=1,c=:blue);
plot(Q_escape,P_escape, ".",markersize=1,c=:red);
xlim(-2.5,2.5) 
ylim(-4.5,4.5) ;

In [21]:
include("negative_time.jl")

back_one (generic function with 1 method)

In [22]:
forward_back=[]

@showprogress for point in cleaned_points
    back_point=back_one(point, t_end, H)
    if back_point!=nothing
        push!(forward_back,back_point)
    end
end

Progress: 100%|█████████████████████████████████████████| Time: 0:03:08m:13


In [23]:
new_forward

724-element Array{Any,1}:
 (1.8949151302491236e-15, -0.5945647385530974, 0.4443489822176144, 2.45549299299467)   
 (-3.45002699132114e-16, -0.9428100623346155, 0.5432209328415848, 2.290660166336763)   
 (6.290719057741426e-15, -1.1163830949437608, 0.6090465659856197, 2.151448219370238)   
 (2.6574354804771087e-16, -1.2232447041922614, 0.6480595145870632, 2.021499521759234)  
 (1.40286206962993e-16, -1.2936731059493658, 0.6642634388024408, 1.8899455425607745)   
 (1.6394087933749738e-16, -1.3399839393685835, 0.6618097500415243, 1.7511145171952496) 
 (7.176441348697169e-16, -1.3797496190802216, 0.6200721049845646, 1.4436649926739948)  
 (-4.698269272602047e-17, -1.3760030118930193, 0.5899825894769714, 1.2734739541490203) 
 (1.4671805661602813e-14, -1.3548813695136361, 0.5583702694252126, 1.0894367855449396) 
 (-3.7684262818674675e-15, 1.354881369513636, 0.5583702694252132, -1.089436785544958)  
 (-3.788080696790967e-15, 1.3760030118930189, 0.5899825894769711, -1.2734739541490203) 
 (1.92

In [24]:
cleaned_points

3931-element Array{Any,1}:
 (0, -1.3863636363636365, 0.6135331487539595, 0.0, 3.739740135899555e-16, -0.5946491183532561, 0.4442305821411961, 2.4554001049061975)              
 (0, -1.3409090909090908, 0.5908885858131729, 0.0, 1.232181681798617e-16, -0.9429562114325443, 0.5430339372692075, 2.2904416666647003)              
 (0, -1.2954545454545454, 0.5700004087791751, 0.0, -1.3698511862005405e-16, -1.116480116851568, 0.6089185586599603, 2.1512435339666043)             
 (0, -1.25, 0.550791581576226, 0.0, 4.1066228496232755e-17, -1.2234520062389092, 0.6479311898359523, 2.0211197749319467)                            
 (0, -1.2045454545454546, 0.5332008659222875, 0.0, 2.0232982611045478e-16, -1.2937546328656535, 0.6641328488006596, 1.889701681348685)              
 (0, -1.1590909090909092, 0.5171814951517396, 0.0, 2.6912825417713196e-16, -1.3400608265931142, 0.6615906373279072, 1.7507420479635232)             
 (0, -1.0681818181818181, 0.48973791932380323, 0.0, -1.0762319641870393e-16, -1

In [25]:
Q0,P0=unzipper2(new_forward)
Q_escape=vcat(Q0,-Q0); P_escape=vcat(P0,-P0);
Q,P=unzipper2(cleaned_points)
Q_one=vcat(Q,-Q); P_one=vcat(P,-P);
Q1,P1=unzipper2(forward_back)
Q_b=vcat(Q1,-Q1); P_b=vcat(P1,-P1);
plot(Q0,P0, ".",markersize=1,c=:blue);
plot(Q,P, ".",markersize=1,c=:red);
plot(Q1,P1, ".",markersize=1,c=:green);

xlim(-2.5,2.5) 
ylim(-4.5,4.5) 

(-4.5, 4.5)

In [26]:
forward_back

211-element Array{Any,1}:
 (1.5926267398890446e-14, -0.5945647385530778, 0.44434898221761937, -2.4554929929946794)
 (-2.667843807555958e-16, -0.9428100623346184, 0.5432209328415831, -2.2906601663367607) 
 (-1.0999432748283918e-16, -1.1163830949437596, 0.6090465659856185, -2.1514482193702382)
 (-1.8101068526845667e-16, -1.2232447041922616, 0.648059514587065, -2.0214995217592358) 
 (-1.4525140539427723e-16, -1.2936731059493685, 0.6642634388024415, -1.8899455425607716)
 (-2.066961160505095e-16, -1.3399839393685848, 0.6618097500415238, -1.7511145171952476) 
 (-1.9294727569991655e-14, -1.3797496190802256, 0.6200721049845631, -1.4436649926739742)
 (3.788080696790967e-15, -1.3760030118930189, 0.5899825894769711, -1.2734739541490203)  
 (3.7684262818674675e-15, -1.354881369513636, 0.5583702694252132, -1.089436785544958)   
 (-1.4671805661602813e-14, 1.3548813695136361, 0.5583702694252126, 1.0894367855449396)  
 (4.698269272602047e-17, 1.3760030118930193, 0.5899825894769714, 1.2734739541490203)

In [27]:
log10(200)

2.3010299956639813

In [121]:
@load "escape_TIME_cdata0_250000001000.bson" SAVE_DATA

In [122]:
time_to_exit=SAVE_DATA["escape_times"]
mesh=SAVE_DATA["mesh"]
ArrP=SAVE_DATA["ArrP"]
ArrQ=SAVE_DATA["ArrQ"]
width = 2.5;
height=5;
logz=log1p.(time_to_exit);
mesh_P=[P for Q in ArrQ, P in ArrP];
mesh_Q=[Q for Q in ArrQ, P in ArrP];
M,N=size(logz)
# for i in 1:M
#     for j in 1:N
#         if isnan(logz[i,j])
#             logz[i,j] = 0
#         end
#     end
# end
ArrP = range(-width, stop = width, length = N)


-2.5:0.005005005005005005:2.5

In [126]:
pcolormesh(ArrP,ArrQ,logz)
pcolormesh(reverse(ArrP),-ArrQ,logz)
colorbar()

PyObject <matplotlib.colorbar.Colorbar object at 0x7fdb4b04d908>

In [112]:
contourf(ArrP,ArrQ,logz)
contourf(reverse(ArrP),-ArrQ,logz)
colorbar()

PyObject <matplotlib.colorbar.Colorbar object at 0x7fdae790abe0>

In [65]:
size(logz)

(1000, 1000)

In [74]:
for i in 1:1000
    for j in 1:1000
        if isnan(logz[i,j])
            logz[i,j] = 0
        end
    end
end

In [77]:
logz

1000×1000 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  

In [61]:
isnan(NaN)

true

In [94]:
ArrQ

0.0:0.005005005005005005:5.0

In [102]:
SAVE_DATA

Dict{String,Any} with 5 entries:
  "ArrQ"         => 0.0:0.0016672224074691564:5.0
  "ArrP"         => -2.5:0.0016672224074691564:2.5
  "Energy"       => 0.25
  "mesh"         => Tuple{Float64,Float64}[(-2.5, 0.0) (-2.49833, 0.0) … (2.498…
  "escape_times" => [NaN NaN … NaN NaN; NaN NaN … NaN NaN; … ; NaN NaN … NaN Na…